codecov:
    name: Coverage
    needs: [test]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1 # to avoid failing tests because of API Rate limits
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
        python-version: ["3.11"]

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -r requirements.txt

      - name: Install package
        run: python setup.py install

      - name: Generate coverage report
        run: |
          pip install pytest pytest-cov
          pytest --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
