name: Pre-Commit

on:
  push:
    branches: ["*", "!master"]
  pull_request:
    branches: ["*"]

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
